### ISSUE TITLE
Añadir a la documentación

### ISSUE THREAD

**Issue by migueabellan** [PCBPrints/Alhambra-button#1]
Hola Juan, me he vuelto loco al crear este botón utilizando una resistencia de 4K7... porque en los pines de 5V (D13...) no funcionaba... además una cosa curiosa es que el pin se queda viciado con valor inestable... al acceder al apartado del tutorial he visto cual era mi error... 
Creo que podría ser buena idea añadir aquí también lo que tienes en el apartado del tutorial:

- Cuando lo conectamos a los pines de 3.3v de la Icezum Alhambra (GPx), los valores típicos de la resistencia que usaremos serán entre 1K y 100K 
- Para la conexión a los pines de 5v, usamos el mismo esquema que para los de 3.3v pero la resistencia de pull-down tiene que estar entre 470ohm y 2K. El valor recomendado es de 1K

Un saludo!

**Comment by migueabellan** [comment]
Le estoy dando vueltas... y crear la misma PCB que sea compatible para los pines 5V y 3V3... Con las dos resistencias y 4 conectores serigrafiados.. así se puede usar para ambos pines...

Un saludo!

**Comment by Obijuan** [comment]
Hecho! Muchas gracias!  :-)

https://github.com/PCBPrints/Alhambra-button/wiki#nota-sobre-los-pulsadores-en-la-placa-icezum-alhambra

Créditos:
https://github.com/PCBPrints/Alhambra-button/wiki#cr%C3%A9ditos
